name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: Production # secrets이 아닌 environment를 사용할 경우, github repo > settings > environments 에서 미리 정의해둬야 함

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. S3로 파일 업로드 (sync 명령 사용)
      - name: Upload to S3
        run: |
          aws s3 sync ./web/light s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # 4. CloudFront 캐시 무효화 (/*)
      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"